name: CI
on:
  push:
    paths-ignore:
      - "*.md"
      - ".vscode/**"
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    paths-ignore:
      - "*.md"
      - ".vscode/**"
jobs:
  biome:
    runs-on: ubuntu-24.04
    timeout-minutes: 3
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        env: [src]
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Run reviewdog with eslint
        uses: mongolyy/reviewdog-action-biome@v2.7.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filter_mode: diff_context
          fail_level: error
          reporter: github-pr-review
          workdir: ${{ matrix.env }}
